#!/bin/sh

set -e

(
  cd /var/lib/sql-ledger ; 
  chown www-data:www-data users templates
  chown -R www-data:www-data css
)

if ! test -L /usr/lib/sql-ledger; then
    # Work around dpkg bug (can't replace dir by symlink itself)
    (rmdir /usr/lib/sql-ledger && ln -sf /usr/share/sql-ledger /usr/lib/sql-ledger) || \
    echo "WARNING: Unable to replace /usr/lib/sql-ledger by a symlink"
fi

#DEBHELPER#
